- name: instalando pacotes pre reqs
  package:
   name: "{{item}}"
   state: present
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common

- name: adicionando a chave do repositorio docker
  apt_key: 
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present

- name: instalando o repositorio
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
   state: present



